### ISSUE TITLE
[BD] Corrigir Banco de dados

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#11]
1. Mudar o nome o nome da Tabela Módulos para 'Grupo'

2. Criar campo de descrição para cada uma das permissões na Tabela Permissões.

**Comment by MacSoares** [comment]
As migrations estão prontas, porém ao serem rodadas, não criam os relacionamentos entre tabelas. Busqueii documentação no CodeIgniter mas não consegui encontrar nada relacionado.

**Comment by MacSoares** [comment]
Migrations finalizadas. O framework CodeIgniter não dá possibilidade de relacionamento de tabelas por chaves estrangeiras nos códigos de migrations. Isso deve ser feito em nível de código ou os relacionamentos devem ser adicionados utilizando o phpMyAdmin
