### ISSUE TITLE
LInha de pesquisa da disciplina

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#112]
Como **secretário acadêmico** (de um curso), desejo relacionar as disciplinas do currículo do curso a uma linha de pesquisa, para que tenha controle do **currículo acadêmico do curso**.
------
1 Linha de Pesquisa : N disciplinas
 * A secretaria deve relacionar a disciplina com a linha de pesquisa no momento que estiver criando o currículo do curso.
 * Deve ser possível editar a linha de pesquisa de uma disciplina
 * A linha de pesquisa é opcional
  * Nenhum
  * Linha de Pesquisa 1
  * Linha de Pesquisa N

**Comment by fillipefeitosa** [comment]
Cadastro de Linha de pesquisa fica dentro do curso

**Comment by MacSoares** [comment]
O cadastro de linha de Pesquisa está como opção dentro das confirmações do curso
