### ISSUE TITLE
Realizar Pagamento

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#114]
Como **secretário financeiro** (de um curso) desejo realizar um pagamento na página *expensePayments* para que eu automatize a solicitação de pagamento de professores e apoios técnicos.

--------------------------------
Critérios de Aceitação
Existem dois tipos de pagamento:
 1. Para pessoa física (ex.: Fillipe O Feitosa) 
  1.1.  Adicionar 339036 .**35** na solicitação
 2. Para um professor - GECC (ex.: Profa. Olgamir Carvalho)
  2.1. Adicionar 339036.**28** na solicitação
 * O secretário escolhe qual o tipo de pessoa ele irá fazer a solicitação de pagamento.
 * Ao informar os dados necessários, será gerado o documento **PROPOSTA SIMPLIFICADA DE PRESTAÇÃO DE SERVIÇOS**
 * Este documento deve ficar à disposição para impressão dentro do Siga.

Modelo da Proposta simplificada de prestação de serviços: 
http://www.daf.unb.br/images/DCF/formuManuais/prop_part_int-ext.xls

**Comment by fillipefeitosa** [comment]
Italo, preciso de um merge o quanto antes dessa US.
Como está o andamento?

**Comment by italopaiva** [comment]
A classe que eu tentei usar deu ruim. Estou tentando outra alternativa.

**Comment by italopaiva** [comment]
Problema com a classe resolvido! Já ta gerando a planilha. Tá um pouco desformatado, mas funcionando.

**Comment by italopaiva** [comment]
Parte do parcelamento será atendida pela issue #125.
