### ISSUE TITLE
Tabela Permissões

### ISSUE THREAD

**Issue by MacSoares** [Sistema-Integrado-Gestao-Academica/SiGA#12]
Criar uma nova coluna denominada 'routes' na tabela permissions, para que seja devidamente mostrados (com todos os caracteres especiais) na navbar do SiGA os nomes das funcionalidades.

**Comment by italopaiva** [comment]
Issue fechada com a adição da coluna 'route' na tabela de permissão (com arquivo de migration) e devidas correções no código devido às alterações.
