### ISSUE TITLE
Visualizar Matrícula

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#120]
Substituir o campo código pelo campo Matrícula na tabela de visualização de alunos.

http://www.il.unb.br/sip/index.php/course/courseStudents/2

**Comment by fillipefeitosa** [comment]
Ítalo, como está o andamento dessa US?

**Comment by italopaiva** [comment]
Tô tentando fechar ela agora. Só que tem um problema que ta afetando muito: Essa matrícula ainda não é gerada pelo sistema, logo não está associado a nenhum estudante. Preciso saber qual é o padrão dessa matrícula pra poder fazer aqui..
