### ISSUE TITLE
Auto Completar Pagamento: Funcionário

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#124]

**Comment by MacSoares** [comment]
Esperando a descrição exata, mas a priori, estou iniciando o preenchimento com os dados de um usuario salvo no banco

**Comment by fillipefeitosa** [comment]
Como está o andamento dessa US?

**Comment by MacSoares** [comment]
Travado no Ajax, mas trabalhando em cima dele

**Comment by fillipefeitosa** [comment]
Macário, qual a situação dessa issue?
