### ISSUE TITLE
Aplicação da nova interface gráfica Bootstrap AdminLTE

### ISSUE THREAD

**Issue by MacSoares** [Sistema-Integrado-Gestao-Academica/SiGA#13]
Mudança da interface gráfica do sistema para que fique mais inteligível e facilite sua usabilidade

**Comment by MacSoares** [comment]
Preciso que alguém verifique o trabalho realizado na issue #13 para confirmar se ainda falta algo a ser alterado na interface do sistema.

**Comment by fillipefeitosa** [comment]
Está rolando um problema no login, é possível fazer login sem colocar senha.

**Comment by italopaiva** [comment]
Problema no login corrigido pela issue #14 .

**Comment by fillipefeitosa** [comment]
Verifica se rola de colocar as informações de conta no Menu com o nome do usuário, como no exemplo 
http://almsaeedstudio.com/AdminLTE/index.html

**Comment by italopaiva** [comment]
Alguma coisa fez o ajax parar de funcionar na pagina de cursos.

**Comment by MacSoares** [comment]
Aguardo para saber quais informações deverão estar disponíveis no menu dropdown de usuário.
