### ISSUE TITLE
Arrumar listagem de disciplinas

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#132]

**Comment by fillipefeitosa** [comment]
O discente precisa de uma lista simplificada no ato da matrícula para ajudar na escolha das disciplinas da sua solicitação.
http://localhost/siga/index.php/request/studentEnrollment/1/4
na página é importante que sejam listadas as **turmas** (não confundir com as disciplinas), daquele curso, daquela lista de oferta.

**Comment by italopaiva** [comment]
Ta assim mano. Só que tem a opção de pesquisar por parte do nome da disciplina. Mas ta aparecendo as turmas das disciplinas da lista de oferta daquele semestre (A lista de oferta tem que estar aprovada para aparecer la, confere isso).

**Comment by fillipefeitosa** [comment]
Como a gente conversou, deixa a lista aparecendo já de cara, sem a necessidade de clicar em pesquisar.
