### ISSUE TITLE
Dados dos Programas

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#139]
Recuperar os dados cadastrados pelo secretário acadêmico na página inicial do SiGA/SiP.
Criar as abas para que todos os programas do cursos possam ser selecionados e ter suas informações recuperadas.

**Comment by italopaiva** [comment]
**Considerações:**

* Destacar os títulos (Histórico, Contato e Linha de Pesquisa) ,com negrito por exemplo, para diferenciar do texto comum;

* Mostrar alguma coisa quando o programa não tiver os dados cadastrados ainda ou deixar os campos obrigatórios no cadastro (Ver com Feitosa);

* Buscar só 10 programas no banco na página inicial.
