### ISSUE TITLE
Dados de Qualquer programa

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#140]
Criar abas para o "Quadro de Apresentação" da página inicial para selecionar os dados de qualquer programa cadastrado no sistema.
É necessário recuperar os dados para cada um dos programas selecionados.

**Comment by fillipefeitosa** [comment]
M. 

Confirma pra mim se essa issue foi concluida. 
Se tiver sido e estiver ok, sobe ela pra dev.

**Comment by Emiliemorais** [comment]
F.

Essa issue voce colocou junto com a outra que é a 139, e ja ta na dev

**Comment by fillipefeitosa** [comment]
Registrado e Atualizado.
