### ISSUE TITLE
Arrumar gerenciamento da sessão

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#147]
* Criar classe de gerenciamento da sessão
* Salvar sessão no banco de dados

**Comment by italopaiva** [comment]
Resolvida na issue #143.

**Comment by fillipefeitosa** [comment]
Confirmar se a issue foi resolvida e mover para local adequado.

**Comment by italopaiva** [comment]
Não to conseguindo fazer o flashdata funcionar com a sessão salva no banco.

**Comment by italopaiva** [comment]
Nessa versão do Code Igniter que estamos utilizando não funciona o flashdata com a sessão salva no banco. Tentei até mexer no código do framework mas não consegui e é muito arriscado. Vejo duas opções no momento:

*  Atualizar a versão do CodeIgniter para a última (Testei só na 3.0.5 até então). Mais trabalhoso, porém mais adequado, pois existem várias atualizações de melhorias e segurança.
* Limpar os dados da sessão para deixar mais leve, deixando somente os ids dos grupos e consultar o banco toda vez que for fazer uma operação. Mais simples de fazer, porém não suportável a longo prazo.

**Comment by fillipefeitosa** [comment]
Será discutido na reunião.
