### ISSUE TITLE
Criar edital

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#148]
Como **secretário acadêmico** desejo criar no sistema um edital de seleção para que possa registrar um processo seletivo e faça suas devidas customizações.

------------

Obs.: Para efeitos práticos, no sistema o termo **"Abrir um Edital"** significa abrir um processo seletivo.

C.A.
* O secretário pode escolher entre um edital de:
  * Processo Seletivo para Alunos Regulares **(Foco dessas próximas issues)**
  * Processo Seletivo para Aluno Especial
* Deve ser possível submeter um arquivo (** formato pdf**), que é o próprio edital. futuramente o secretário poderá submeter retificações.

**Comment by fillipefeitosa** [comment]
Alinhar pontuação.
