### ISSUE TITLE
Bug fix - Exclusão de um plano orçamentario

### ISSUE THREAD

**Issue by Emiliemorais** [Sistema-Integrado-Gestao-Academica/SiGA#151]
Quando tenta excluir algum P.O. que não seja o primeiro ele aparece a opção pra excluir apenas o primeiro

**Comment by Emiliemorais** [comment]
A exclusão também não funciona.

**Comment by fillipefeitosa** [comment]
adicionar pontuação.

**Comment by Emiliemorais** [comment]
Resolvendo na branch 119
