### ISSUE TITLE
Dados de Docente

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#156]
Como **docente**, desejo inserir um **breve perfil** e um link para o meu **lattes** , para que seja mostrado na página incial da ferramenta (Portal).

-----------------
  
O portal deve ter uma menu **docentes** para cada programa, para todos docentes cadastrados nos cursos daquele programa.
Ao clicar, deve ser possível ver o nome do docente, um **breve perfil** e o link para o **lattes** <a href="link" />

**Comment by fillipefeitosa** [comment]
confirmar pontuação.

**Comment by Emiliemorais** [comment]
Como assim aba de docente? Dentro do programa?

**Comment by fillipefeitosa** [comment]
Sabe o menu 'colapse'? do portal que quando você clica aparecem embaixo os dados? Então, é isso.

**Comment by Emiliemorais** [comment]
Eu vou fazer de um jeito que pensei, ai tu ve se gosta.
