### ISSUE TITLE
Recuperar Senha

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#171]
Como **usuário**, gostaria de ter uma opção de recuperação de senha, para que eu consiga acessar o sistema caso esqueça da mesma.

---------

* Preparar o sistema para trabalhar com encaminhamento de emails. 
* O usuário deve clicar em "Esqueci minha senha". O SiGA irá gerar uma nova senha para ele, e envia-la para o email que ele cadastrou.
* Para garantir que o usuário requeriu sua senha, solicar email de cadastro.

**Comment by Emiliemorais** [comment]
* A senha gerada é temporária e o usuário deverá alterar a senha.
