### ISSUE TITLE
Secretário: Relatório Periódico de Solicitações

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#176]
Como **secretário acadêmico**, desejo receber um email **semanal** (deve ser possível alterar a periodicidade), para que possa tomar as devidas providências dentro da ferramenta.
-------------------

O email deve conter:
* A quantidade de usuários convidados cadastrados no sistema, sem relação com nenhum curso.
* A quantidade de solicitações de documentos feitas para a secretaria, de todos os cursos que  o secretário está vinculado.

**Comment by Emiliemorais** [comment]
Para configurar o envio semanal digitar no terminal
* 00 6 * * 1 \<caminho do php> \<caminho da aplicação e para o index.php> secretaryemail sendEmail
* Exemplo: 00 6 ** 1 /usr/bin/php /home/emilie/SiGA/index.php secretaryemail sendEmail
