### ISSUE TITLE
Atualizar o CodeIgniter

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#196]

**Comment by Emiliemorais** [comment]
@Emiliemorais

**Comment by Emiliemorais** [comment]
* Os passos foram executados
* Problema: Não está carregando a _Session_ e as _libraries_ criadas para o SiGA

**Comment by Emiliemorais** [comment]
* O problema estava acontecendo porque não se pode instanciar _controller_ dentro de _controller_.
* Solução: Separar o SiGA em módulos

**Comment by italopaiva** [comment]
Solução: HMVC - https://bitbucket.org/wiredesignz/codeigniter-modular-extensions-hmvc
