### ISSUE TITLE
[Técnica] Refatorar o uso de User_type

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#20]
Retirar a necessidade do sistema logar usando user_type. 

* O sistema deve:
1. Logar se o usuário possuir conta no sistema
2. Caso ele possua conta no sistema, no mínimo pertencerá ao grupo de convidados
3. Verificar de quais grupos o usuário faz parte. 
4. Montar o "menu lateral", com um item de menu para grupo que o usuário faz parte.

**Comment by MacSoares** [comment]
As funcionalidades continuam plenas, com exceção do menu de cursos, quando acessado ele desloga o usuário "por motivos de segurança", mesmo sendo ele 'admin'

**Comment by MacSoares** [comment]
Bug retirado.

**Comment by MacSoares** [comment]
Isseu #20 concluída. Não existem mais usos de user_type no código
