### ISSUE TITLE
Importar Qualis

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#228]
Importar dados do qualis e atualizar automaticamente no cadastro da publicação.

O usuário pode inserir tanto identificador (ISSN ou ISBN), quanto nome e o sistema deve buscar diretamente no banco esse qualis.

**Comment by Emiliemorais** [comment]
@italopaiva

**Comment by italopaiva** [comment]
***OBS.:*** Para colocar em produção, lembrar de alterar o tamanho máximo de upload para 10MB no php.ini(/etc/php5/apache2/php.ini) e restartar o server.

**Comment by italopaiva** [comment]
Plugin adicionado para decorar o form de escolher um arquivo: http://markusslima.github.io/bootstrap-filestyle/

**Comment by italopaiva** [comment]
O sistema está aceitando apenas CSV, porque não deu pra fazer com XLS, pois o arquivo era muito grande e estava estourando a memoria.
