### ISSUE TITLE
[TÉCNICA] Solicitação de inscrição recusada

### ISSUE THREAD

**Issue by Emiliemorais** [Sistema-Integrado-Gestao-Academica/SiGA#230]
Quando uma solicitação de inscrição é recusada o usuário está sendo salvo na tabela de matrícula (course_student)

**Comment by Emiliemorais** [comment]
@fillipefeitosa Não tem como resolver, porque o erro não ta aparecendo. Já analisei o codigo e está ok

**Comment by fillipefeitosa** [comment]
Verificado.
