### ISSUE TITLE
Projetos - equipe

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#237]
Como participante de um projeto (**docente** ou **discente**), desejo editar a equipe de um projeto, vinculando pessoas do programa (que estão no SiGA) pelo CPF ou adicionando o nome, para que a edição de um projeto não fique tão burocrática.

**Comment by italopaiva** [comment]
Quais as pessoas que podem ser adicionadas em uma equipe de projeto? Docentes e Discentes apenas?

**Comment by italopaiva** [comment]
@italopaiva Teste

**Comment by fillipefeitosa** [comment]
Docentes e discentes, mas terceiros também, a partir do CPF. Um aluno de graduação por exemplo que não esteja registrado no sistema.
