### ISSUE TITLE
[Matrícula - Orientador/Secretaria] Simplificar aprovação de matrícula

### ISSUE THREAD

**Issue by Emiliemorais** [Sistema-Integrado-Gestao-Academica/SiGA#253]
Simplificar a aprovação da matrícula de um aluno para o orientador. 

Opções de solução:

* **Não precisar finalizar a solicitação**
* **Mostrar para o secretário a mesma coisa que pro coordenador**
* **Só ir para o secretário quando tudo tiver aprovado**

**Comment by Emiliemorais** [comment]
** Deixar claro no período de matrícula que após esse período as solicitações não poderão ser modificadas pelo aluno

**Comment by fillipefeitosa** [comment]
O que falta para conclusão?

**Comment by italopaiva** [comment]
@fillipefeitosa Falta só o merge.
