### ISSUE TITLE
Database Erro

### ISSUE THREAD

**Issue by michelmarques1** [Sistema-Integrado-Gestao-Academica/SiGA#265]
Olá Colegas da Comunidade,

Após realizar a instalação do SiGA e tentar acessar:

http://localhost/sistemas/academico/SiGA-master/index.php/migrate

O sistema me retorna o seguinte erro:

Ocorreu um erro de banco de dados

Error Number: 1146

Table 'siga.session' doesn't exist

SELECT `data` FROM `session` WHERE `id` = 'd5dd9dfe77f29c47a178f39c9a69f8d49c234408'

Filename: C:/xampp/htdocs/sistemas/academico/SiGA-master/system/database/DB_driver.php

Line Number: 691

O que será que pode ser?

**Comment by italopaiva** [comment]
@michelmarques1 Olá @michelmarques1! Acho que provavelmente você está rodando o siga pela primeira vez, desse modo o banco de dados ainda não existe, por isso ele não encontra a tabela session (o siga está configurado por default para salvar a sessão no banco de dados). Portanto, basta alterar onde o CodeIgniter irá salvar a sessão no arquivo 'application/config/config.php' (só seguir a observação no passo 6 do tutorial de instalação que está no README). Lembre-se de voltar as configurações para salvar a sessão no banco de dados, depois que rodar as migrations. Qualquer outra dúvida, estamos a disposição! Abraço!

**Comment by michelmarques1** [comment]
@italopaiva , verdade! Realmente havia esquecido desse detalhe rsrs.

Realizei a alteração, rodei o migrate e ao final, veio o seguinte:


Fatal error: Call to undefined method MY_Loader::test_template() in C:\xampp\htdocs\siga\application\controllers\Utils.php on line 8
A PHP Error was encountered

Severity: Error

Message: Call to undefined method MY_Loader::test_template()

Filename: controllers/Utils.php

Line Number: 8

Backtrace:

O que será que pode ter sido?

**Comment by italopaiva** [comment]
@michelmarques1 Como está o seu arquivo 'application/core/MY_Loader.php?

**Comment by michelmarques1** [comment]
@italopaiva , assim:
<?php (defined('BASEPATH')) OR exit('No direct script access allowed');

/* load the MX_Loader class */
require APPPATH."third_party/MX/Loader.php";

class MY_Loader extends MX_Loader {}

**Comment by italopaiva** [comment]
@michelmarques1 Ah sim. Percebi um erro aqui no tutorial. Na verdade não precisa fazer o passo 3 do Modular Extension. Vou atualizar isso em breve. Basta você utilizar o arquivo 'application/core/MY_Loader' que está na nossa master.

**Comment by michelmarques1** [comment]
@italopaiva , consegui!

Só mais uma pergunta, não encontrei no readme. Qual o usuário e senha inicial?

**Comment by italopaiva** [comment]
@michelmarques1 É, realmente não tem no README, mas é 'admin' o usuário e senha.. Ai a partir da conta de admin você pode criar mais usuários e adicionar permissões a eles.

**Comment by michelmarques1** [comment]
Muuito obrigado! Desculpe o incômodo!

**Comment by italopaiva** [comment]
@michelmarques1 Que isso, tranquilo!

**Comment by rminossi** [comment]
Fatal error: Call to undefined method MY_Loader::test_template() in C:\xampp\htdocs\siga\application\controllers\Utils.php on line 8
A PHP Error was encountered

Estou tendo esse erro
