### ISSUE TITLE
Vínculo de Projeto na Produção Intelectual

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#278]
Como **docente** ou **discente**, desejo que o vínculo do projeto na produção intelectual seja obrigatório, **para** que o programa não seja penalizado por existirem produções sem vínculo com o projeto.

----------
Critérios de Aceitação
* A produção intelectual deve estar vinculada a um projeto.

**Comment by fillipefeitosa** [comment]
Favor pontuar.

**Comment by fillipefeitosa** [comment]
Qual o status dessa US?

**Comment by Emiliemorais** [comment]
Tava pronta. So faltava dar merge na dev. Já ta la.
