### ISSUE TITLE
Comparativo do Indicador de Colaboração

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#279]
Como **coordenador** de um curso, desejo visualizar um comparativo do **indicador de colaboração** do meu curso com o de programas de referência numa determinada avaliação base, para que possa verificar o status da produção intelectual do meu programa com a dos programas ponta de linha.

**Comment by Emiliemorais** [comment]
O que são esses programas  de referencia?
