### ISSUE TITLE
Criação de Disciplinas

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#31]
Como **Secretária Acadêmica** (ou **administrador**), desejo manter uma disciplina, para que possa oferecer listas de oferta semestrais.

------------------------------------------------------

Critérios de Aceitação:
* Se necessário, criar um novo grupo com as devidas permissões para Manter Disciplina
* Atributo de Disciplina: Código, Nome, Créditos, Carga Horária
* Carga Horária deve ser automaticamente preenchida pelo sistema, com base nos créditos
* Carga Horária pode ser editada pelo usuário.

**Comment by MacSoares** [comment]
CRUD de disciplinas completo.
