### ISSUE TITLE
Currículo de Curso

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#33]
Como **secretária acadêmica** [de determinado Curso] desejo alocar disciplinas (issue #31) no **Currículo** de determinado **Curso de Pós-Graduação** (issue #5 ) para que possa organizar corretamente a lista de oferta do meu curso a partir dos cursos existentes no sistema.

 ------------------------

**Comment by italopaiva** [comment]
Issue reaberta para correção da lista de disciplinas que aparecem para montar a lista de oferta. A lista de disciplinas deve conter apenas as disciplinas que estão no currículo do curso.

**Comment by italopaiva** [comment]
Lista de disciplinas corrigida.
