### ISSUE TITLE
Rever a Modelagem de Grupos

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#34]
Para o correto funcionamento do sistema, é necessário rever o uso da tabela *secretary_course*, verificando se os logins e os menus estão sendo criados corretamente, a partir da tabela.

Rever os usos, e procurar por bugs.

**Comment by MacSoares** [comment]
Criação de grupos para secretarias com permissoes para um curso no momento da criação deste curso.

**Comment by fillipefeitosa** [comment]
É importante lembrar que existem duas secretarias(acadêmica e financeira). Os dois grupos precisam ser criados quando um curso é cadastrado.

**Comment by MacSoares** [comment]
Issue finalizada e merge feito para branch development.
