### ISSUE TITLE
Manter Programa de Pós-Graduação

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#39]
Como **administrador**, desejo manter um programa de Pós-Graduação, para que possa organizar os **cursos** de pós dentro desses **programas**.

-------------------
Critérios de Aceitação
* É necessário editar as informações de um programa
* Atributos:
 * Nome
 * Sigla
 * Coordenador [**usuário do sistema**]
 * Ano de Abertura
* É necessário relacionar cursos com programa [**Programa 1:N Cursos**]

**Comment by italopaiva** [comment]
Issue finalizada com correções necessárias a inconsistências inerentes a issue #36 .
