### ISSUE TITLE
Orientador

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#43]
**Como** secretária acadêmica (*de determinado curso*), **desejo** definir  um orientador (docente) para um discente devidamente inscrito neste curso, **para** que cada aluno do curso tenha um orientador a fim de auxiliar no fluxo acadêmico.

--------------------------------

 * Para que essa funcionalidade funcione corretamente, é necessário que os grupos estejam definidos de forma correta. Esse é um ponto chave da ferramenta, pois um secretário do curso A não pode manter dados no curso B e vice-versa.
 * Para tanto, **confirmar se os grupos (*secretaria acadêmica e financeira*) estão sendo criados**  no momento da criação do curso.

**Comment by fillipefeitosa** [comment]
Italo, favor verificar a situação dessa issua em sua branch e continuar com a implementação.

**Comment by fillipefeitosa** [comment]
Macário, como está essa Issue?

**Comment by MacSoares** [comment]
Issue finalizada
