### ISSUE TITLE
Enviar Solicitação de Matrícula [Discente]

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#45]
Como discente, desejo escolher as disciplinas (enquanto houverem vagas) que irei cursar e submeter para aprovação do meu orientador, para que ele possa analizar a minha solicitação, aprovar ou recusar.

---------------------

Atributos de uma solicitação:
 1. status: 
   * Incompleto: do momento em que o período de matrícula abre, até o momento que o discente submete sua solicação
   * (em) Aberto: quando o orientador aprova a solicitação, disponibilizando para a secretaria
   * Recusado: quando o orientador recusa a solicitação, ou alguma disciplina em específico, para que o aluno possa fazer modificações novamente.
   * Matriculado: quando a secretaria acadêmica recebe a solicitação aprovada e confirma a matrícula.
 2. Semestre Corrente: registra no banco qual o semestre dessa solicaitação.

**Além dos identificadores da solicitação e do discente.**

----------------------

C.A.:
 1 - É importante que as vagas sejam respeitadas. As vagas para a oferta de determinada disciplina são consumidas no momento em que a disciplina é escolhida.
 2 - O aluno pode alterar à vontade sua **solicação** (conjunto de disciplinas para sua matrícula), até que submeta e a solicação mude seu status para **aprovado**  
 3 - Como o aluno pode alterar sua solicitação à vontade antes de submetê-la, as vagas devem ser ajustadas no momento que ele solicita a disciplina, ou a retira da sua solicitação.

**Comment by italopaiva** [comment]
Core da issue finalizado.
Falta adicionar horário às turmas cadastradas, déficit que será coberto pela issue #47 .
