### ISSUE TITLE
[TÉCNICA] Corrigir erros na atribuiçao de secretarias aos usuários

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#50]
Corrigir:

- Ao atribuir as secretarias, o mesmo usuário é cadastrado com o mesmo grupo na tabela user_group várias vezes.

- Dropdown dos secretários disponibiliza todos usuários para serem definidos como secretários.

**Comment by MacSoares** [comment]
Bugs resolvidos.
