### ISSUE TITLE
Relatório de solicitações - Orientador

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#53]
Como **Orientador**, desejo acessar um relatório das solicitações de todos os alunos (que são meus *orientandos*), indicando o status da solicitação, devidamente ordenados por status, para que possa acompanhar o processo de matrícula dos meus orientados e **aprovar** a solicação para efetuar a matrícula.

---------------

C.A:
1. Diferenciar as solicitações no relatório  por cor: Verde para aprovado, vermelhor para recusado, normal para concluído.

2. Futuramente (próxima issue na sequência), o orientador poderá:
   * Deixar ua mensagem, vinculada à solicatação, caso recus
   * Recusar uma disciplina e aprovar outras, recusando a solicitação;
   * Recusar a solicação Inteira

3. Criar botão de "Detalhar", para acessar as disciplinas na solicitação

**Comment by MacSoares** [comment]
Issue finalizada.
