### ISSUE TITLE
[TÉCNICA] Validar arrays nas models 

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#55]
Utilizar o método criado pela issue #51 ( checkArray() na models_helper) para validar os arrays retornados de consultas ao banco de dados nos arquivos models.

OBS.: Algumas models já foram refatoradas, refatorar as restantes.

**Comment by MacSoares** [comment]
Issue Finalizada. Todas as modelos possuem metodos de validação de array, nas funções necessárias.
