### ISSUE TITLE
[TÉCNICA] Deletar código usado para ajax

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#56]
Como a forma de gerenciar os cursos mudou, deletar código morto utilizado para o AJAX no cadastro de cursos.

Arquivos identificados que contém código morto: funtions.js, course.php.

*OBS.: Procurar por mais arquivos que possam conter código morto.*

**Comment by italopaiva** [comment]
Código relacionado com a especificação dos programas entre *professional_program* e *academic_program* na course controller (e dependentes) também devem ser apagados, pois agora os programas são regidos pela controller *program*.

**Comment by MacSoares** [comment]
Somente estes dois arquivos possuíam código Ajax inutilizado.
