### ISSUE TITLE
Cadastro de Cursos de Pós-Graduação

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#6]
Como administrador, desejo poder selecionar qual tipo de Pós-Graduação (Programa Acadêmico[Mestrado/Doutorado], Programa Profissional), para que possa definir os tipos de funcionalidades disponíveis para cada um dos cursos. 

Obs.: 
- O programa profissional pode ser Financiado($), ou não.(OBSOLETO, Planos Orçamentários podem ser criados e vinculados a um programa de pós)
- Apresentar duração mínima(18 meses), regular(24 meses) e máxima do curso(30 meses).

**Comment by italopaiva** [comment]
Correções necessárias feitas após fechamento da issue por falta de métodos 'CRUD' para os doutorados e por alterações na estrutura do banco de dados.
