### ISSUE TITLE
Correção do status da solicitação (Secretaria discente)

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#66]
- Pegar solicitações que foram aprovadas pelo coordenador para passar para secretária.

- Mudar status (no contexto da secretária) da solicitação para "Matriculado".

**Comment by fillipefeitosa** [comment]
Cuidado:

A secretaria continua listando todas as solicitações.

A **Secretaria** SÓ consegue Matricular o que foi **aprovado**
