### ISSUE TITLE
Coordenador

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#71]
Como **Coordenador**, desejo poder visualizar a situação do meu programa, para que tenha um relatório geral (de alto nível) dos cursos do meu programa.
 --------------------
C.A.
 * Lembrar que 1 Programa : N cursos
 * **Coordenador** só visualiza os dados do seu programa.
 * O **coordenador** é na verdade um **Docente**(professor) com mais persmissões de acesso!
 * O **coordenador** deve ter acesso aos seguintes relatórios:
  * Cursos
  * Alunos
  * Funcionários (relacionados por função)

**Comment by italopaiva** [comment]
Essa parte dos funcionários não está definida no sistema ainda. Não dá pra gerar relatórios sobre isso.
