### ISSUE TITLE
Avaliação: Estrutura Básica

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#72]
Como **Administrador** desejo visualizar a avaliação dos programas do sistema, para que possa acompanhar em tempo real a condição de cada programa frente a avaliação da **CAPES**.

--------------

 * Construir a estrutura básica para abrigar a **Avaliação** para os N programas dentro do software. 
 * Cada programa possui uma avaliação, que deve baseada num tempo. (4 anos), ou seja de 4 em 4 anos o programa recebe uma nota. 
 * Deve ser possível alterar a periodicidade da Avaliação (de 4 anos para 3 anos por exemplo, ou 5 anos). 
 * Atenção para próxima issue na sequência: A avaliação possui "parciais" anuais. Atenção para não limitar a classe.

**Comment by fillipefeitosa** [comment]
Macário. Como está essa issue?

**Comment by MacSoares** [comment]
Quando eu implementei o observer,  não sei oq aconteceu, q deu um bug louco e quebrou a aplicação. Dai tive q voltar meus commits e recomeçar. Estou no meio da reimplementação do observer
