### ISSUE TITLE
Dimensão de Avaliação

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#73]
A avaliação é composta de 5 dimensões:

 * Proposta do Programa
 * Corpo Docente
 * Corpo Discente
 * Produção Intelectual
 * Inserção Social

**Entidade**: Dimensão
**Relacionamento**: 1 Avaliação : N Dimensões
**Atributos**:
 * Peso: porcentagem, a soma dos pesos dos 5 itens deve ser 100% (tratar exceção)
 * Nome: o nome da dimensão
 * Nota: Nota bruta do indicador (vai depender de outras issues)
 * Fragilidade: comentário automático que descreve os itens frágeis dentro da dimensão
----------------------------------

C.A.
 * Tratar a somatória dos pesos, não deve ser maior que 100%
 * As 5 acima Dimensões são padrão, não podem ser apagadas. Mas podem ser desativadas na conta, ao clicar num botão **desativar** setar o peso da dimensão para 0%
 * Deve ser possível criar uma nova dimensão, dentro das mesmas regras.

**Comment by fillipefeitosa** [comment]
Atenção
 * 1 dimensão : n indicadores

**Comment by italopaiva** [comment]
Refatorar parte dos dados de uma dimensão, quando for feita a parte dos indicadores.

**Comment by italopaiva** [comment]
Questão da criação de novas dimensões atendidas pela issue #78.

**Comment by italopaiva** [comment]
Questão do gerenciamento dos pesos atendida pela issue #79.
