### ISSUE TITLE
Criar Via de Pagamento (1)

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#84]
Como **secretário financeiro** (de um curso), desejo criar um uma via de pagamento na página de **Adicionar Despesa** em **Plano Orçamentário**, para que eu possa automatizar o registro de pagamentos para pessoas físicas e do quadro de servidores.

---------
Essa é a 1ª US de uma série para uma série de via de pagamento. 
O objetivo final é gerar uma guia completa de pagamento a partir de um modelo, direto no sistema. 

**Critérios de Aceitação** para Esta US:
 * Botão **Pagamentos** na página de novas despesas -> redireciona para nova página
 * Selecionar entre duas opções
  * Pessoa Física
  * Servidor (GECC)
 * Informar valor total do pagamento. Deduzir esse valor do Montante daquele Plano Orçamentário.
 * Plano Orçamentário 1 : N Vias de Pagamento

**Comment by italopaiva** [comment]
** Atualização da issue **

* Para criar um pagamento, cria-se uma despesa do tipo "Outros Serviços de Terceiros (códigos 339036 e 339039)" e dentro dessa despesa tem a opção de criar um pagamento.
    * Somente para as despesas de natureza "Outros Serviços de Terceiros (códigos 339036 e 339039)".
    * Despesa 1 : N Pagamentos.
* Fazer, inicialmente, somente para pessoa física.
