### ISSUE TITLE
Lista de disciplinas por curso

### ISSUE THREAD

**Issue by italopaiva** [Sistema-Integrado-Gestao-Academica/SiGA#93]
Como **secretário acadêmico** desejo visualizar a lista de disciplinas dos cursos os quais sou secretário para organizar a grade curricular do meu curso.

**Comment by italopaiva** [comment]
Depende da issue #92.

**Comment by MacSoares** [comment]
Não é resolvida junto da issue #92?

**Comment by fillipefeitosa** [comment]
Ok. Issue fechada.
