### ISSUE TITLE
Relatório Geral - Coordenador

### ISSUE THREAD

**Issue by fillipefeitosa** [Sistema-Integrado-Gestao-Academica/SiGA#97]
Como **Coordenador** desejo visualizar um relatório geral do curso ao qual sou coordenador, para que tenha controle das atividades.

-----
C.A.
O coordenador deseja visualizar :
 * Um quadro resumo dos discentes do  programa/curso.
 * Um quadro resumo dos docentes do  programa/curso.
 * Um quadro resumo dos funcionários (secretarias) de um programa/curso.

**Comment by MacSoares** [comment]
Descrição dos quadros de resumo

* Quadro resumo Discentes :   Quantos alunos existem, quantos matriculados, quantos atrasados... 
* Quadro resumo Docentes: Quantos docentes existem cadastrados, numero de orientandos cada docente possui...
* Quadro resumo secretarias:  qual curso e que tipo de secretaria é registrado
